### PR TITLE
Remove extra trailing slash from URLs

### LINKED ISSUE #229: Production builds fail with a bad base URL for linked files
Production builds set `<base href="https://anno.tate.org.uk//">` in the head of the page, which then breaks the site because URLs like https://anno.tate.org.uk//css/main.css don't resolve to https://anno.tate.org.uk/css/main.css.

I'd recommend just removing the `<base>` tag from the HTML, and writing out full file paths for URLs where necessary.

### PR DESCRIPTION
**Pull request by eatyourgreens**
Remove an extra trailing slash from CSS and JS file paths in index.html.

Fixes #229.

### CODE REVIEW

**Comment by eatyourgreens** [comment]
In theory, this should automatically deploy to https://preview.zooniverse.org/annotate.

File: gulp/tasks/s3-paths.js [hunk 1]
```diff
@@ -16,11 +16,10 @@ gulp.task('s3Paths', function () {
 
         gulp.src(filename)
 
-            .pipe(replace(/[ ](href|src)="(?!http)/g, ' $1="' + baseUrl + '/'))
-            .pipe(replace(/(url\(")/g, ' $1' + baseUrl))
-
             // Base tag, needed for ui-router
             .pipe(replace('<base href="/">', '<base href="' + baseUrl + '">'))
+            .pipe(replace(/[ ](href|src)="(?!http)/g, ' $1="' + baseUrl))
```
Comment (shaunanoordin) [inline gulp/tasks/s3-paths.js]: A small note here: the intent of this line is to change all relative links to absolute links, e.g. `` to `<img src="https://anno.tate.org.uk/images/art.jpg"` and, with this PR update, it only really works if the href/src _doesn't_ start with a slash.

I want this in writing because it took me a while to understand that "negative lookahead" Regex code and I'll be darned if I forget it.

**Comment by eatyourgreens** [comment]
BASE_URL doesn't have a trailing slash in the build scripts. https://github.com/zooniverse/AnnoTate/blob/8de148f6cd3b1bde66484690d5a1319c0064fd5f/Jenkinsfile#L17-L29

The string replacement in the gulp file was adding a / to the end of the string, even though one was already present in the href attribute ie. it converts `href="/"` to `href="https://anno.tate.org.uk//"`.

File: gulp/tasks/s3-paths.js (hunk 1 above)
Comment (eatyourgreens) [reply gulp/tasks/s3-paths.js]: I still don't completely understand this regex.
